#!/bin/bash

# 🎬 Add Video to Xcode - Automated Script

clear
echo ""
echo "🎬 Adding PitchMe.MP4 to Xcode Project"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Check if video exists
if [ ! -f "Pitch Me/Resources/PitchMe.MP4" ]; then
    echo "❌ Error: PitchMe.MP4 not found in Pitch Me/Resources/"
    echo ""
    echo "Please move your video to: Pitch Me/Resources/PitchMe.MP4"
    exit 1
fi

echo "✅ Video file found: Pitch Me/Resources/PitchMe.MP4"
echo "📦 Size: $(du -h 'Pitch Me/Resources/PitchMe.MP4' | cut -f1)"
echo ""

echo "🔧 To add the video to Xcode, follow these steps:"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 1: Open Xcode"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "   open 'Pitch Me.xcodeproj'"
echo ""

read -p "Press Enter when Xcode is open..."

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 2: Add Video to Project"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "In Xcode:"
echo ""
echo "  1. In the left sidebar (Project Navigator),"
echo "     find and RIGHT-CLICK on 'Pitch Me' folder"
echo ""
echo "  2. Select: 'Add Files to \"Pitch Me\"...'"
echo ""
echo "  3. Navigate to and select:"
echo "     Pitch Me/Resources/PitchMe.MP4"
echo ""
echo "  4. ⚠️  IMPORTANT - Check these boxes:"
echo "     ✅ Copy items if needed"
echo "     ✅ Create groups"
echo "     ✅ Add to targets: Pitch Me"
echo ""
echo "  5. Click 'Add'"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 3: Verify & Run"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  1. In Project Navigator, you should see:"
echo "     📁 Resources"
echo "        └── 🎬 PitchMe.MP4"
echo ""
echo "  2. Click on PitchMe.MP4"
echo ""
echo "  3. In File Inspector (right panel):"
echo "     Check: Target Membership: ✅ Pitch Me"
echo ""
echo "  4. Clean & Build:"
echo "     Press: ⌘⇧K (Clean)"
echo "     Then:  ⌘B (Build)"
echo ""
echo "  5. Run the app:"
echo "     Press: ⌘R"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🎉 Your video will now play on app launch!"
echo ""
echo "💡 If you still see the animated splash instead,"
echo "   it means the file isn't in the bundle yet."
echo "   Make sure to check ALL the boxes in Step 2!"
echo ""

